# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: alt-tab.io
subtitle: 'Adventures in context switching'
description: 'A blog about software development and its intersections with personal life, hobbies and interests.'
keywords: 'software engineering,software architecture'
author: Matthew Corven
language: en
timezone: 'America/New_York'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://alt-tab.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: https://github.com/matthewcorven/alt-tab
  # example, https://github.com/hexojs/hexojs.github.io
  branch: gh-pages

feed:
    limit: 20
    order_by: "-date"
    tag_dir: "tag"
    category_dir: "category"
    rss:
        enable: true
        #template: "themes/theme/layout/_alternate/rss.ejs"
        output: "rss.xml"
    atom:
        enable: true
        #template: "themes/theme/layout/_alternate/atom.ejs"
        output: "atom.xml"
    jsonFeed:
        enable: true
        #template: "themes/theme/layout/_alternate/json.ejs"
        output: "feed.json"

html_prettify:
    enable: true
    exclude:
        - "*/**/test"
    options:
        indent_size: 2
        indent_char: " "
        max_preserve_newlines: "-1"
        preserve_newlines: false
        keep_array_indentation: true
        break_chained_methods: false
        indent_scripts: normal
        brace_style: expand
        space_before_conditional: true
        unescape_strings: false
        jslint_happy: true
        end_with_newline: true
        wrap_line_length: "0"
        indent_inner_html: false
        comma_first: false
        e4x: false
        indent_empty_lines: false

broken_links_checker:
    frontmatter:
        - links
    timeout: 1000
    useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68'
    parallel: 10
    cache:
        enable: true
        lifetime: 1440
        path: 'link-checker.json'

marked:
  smartypants: false
  # Embedding an image using markdown
  # https://hexo.io/docs/asset-folders#Embedding-an-image-using-markdown
  # Once enabled, an asset image will be automatically resolved to its corresponding post's path. 
  # For example, "image.jpg" is located at "/2020/01/02/foo/image.jpg", meaning it is an asset image 
  # of "/2020/01/02/foo/" post, ![](image.jpg) will be rendered as <img src="/2020/01/02/foo/image.jpg">.
  prependRoot: true
  postAsset: true

opengraph_image:
  enable: true
  main_color: '#fff'
  secondary_color: "#000"
  font_color: "#000"
  title_font: "Bold 70pt Arial"
  date_font: "Regular 30pt Arial"
  date_style: "YYYY/MM/DD"